name: urdf_cq
channels: [conda-forge]
channel_priority: strict
dependencies:
  - python=3.10
  - cadquery
  - numpy
  - matplotlib>=3
  - pandas>=1.0
  - pyyaml>=5.4.1
  - trimesh
  - pip
  - pip:
      - yourdfpy
      - xacro

